name: CMake C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [native, second] # second - clang for linux, mingw gcc for win
        include:
          - os: ubuntu-latest
            compiler: second
            cmake_opts: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          - os: windows-latest
            compiler: second
            cmake_opts: -G "MSYS Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake . -Wdev ${{ matrix.cmake_opts }}
    - name: build
      run: cmake --build . # --verbose
    - name: test
      run: ctest --extra-verbose
